Add missing include of config.h
Without this, linking fails on mingw when configured with
--disable-shared because PCRE2_STATIC doesn't get defined, leading
to pcre2posix.h incorrectly enabling use of __declspec(dllimport).
The errors look like:

c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: src/pcre2posix_test-pcre2posix_test.o:pcre2posix_test.c:(.text.startup+0x6f): undefined reference to `_imp__pcre2_regcomp'