build: fix required autoconf version
Since abc2ae68 (Update AX_PTHREAD (#694), 2025-02-12), when using
autoconf 2.60 with autogen, shows:

  error: possibly undefined macro: AS_ECHO

Use 2.62 instead, which include that macro, as the new required version.